INSERT INTO courses (course_name) VALUES ('Bsc Computer Science');
INSERT INTO courses (course_name) VALUES ('Physics');
INSERT INTO courses (course_name) VALUES ('Mathematics');
INSERT INTO courses (course_name) VALUES ('Chemistry');
INSERT INTO courses (course_name) VALUES ('English Literature');
INSERT INTO courses (course_name) VALUES ('History');
INSERT INTO courses (course_name) VALUES ('Psychology');
INSERT INTO courses (course_name) VALUES ('Business Administration');
INSERT INTO courses (course_name) VALUES ('Sociology');
INSERT INTO courses (course_name) VALUES ('Art History');
